# Generated by Django 5.1.4 on 2026-05-05 06:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Conversation Title')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('EMPLOYEE', 'Employee Data'), ('POLICY', 'HR Policy'), ('LEAVE', 'Leave Policy'), ('PAYROLL', 'Payroll Info'), ('ATTENDANCE', 'Attendance Policy'), ('GENERAL', 'General HR Info')], default='GENERAL', max_length=20)),
                ('content', models.TextField(verbose_name='Content')),
                ('embedding', models.JSONField(blank=True, help_text='Vector embedding as JSON array (1536 dimensions)', null=True, verbose_name='Embedding Vector')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Source document metadata (ID, type, date, etc.)', verbose_name='Metadata')),
                ('chunk_index', models.PositiveIntegerField(default=0, verbose_name='Chunk Index')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Embedding',
                'verbose_name_plural': 'Document Embeddings',
                'ordering': ['document_type', 'chunk_index'],
                'indexes': [models.Index(fields=['document_type'], name='chatbot_doc_documen_d3b338_idx'), models.Index(fields=['is_active'], name='chatbot_doc_is_acti_1d223a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10, verbose_name='Role')),
                ('content', models.TextField(verbose_name='Content')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Stores token count, model info, sources, etc.', verbose_name='Metadata')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='Tokens Used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation', verbose_name='Conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Thumbs Down'), (2, 'Neutral'), (3, 'Thumbs Up')], verbose_name='Rating')),
                ('feedback_text', models.TextField(blank=True, verbose_name='Feedback Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chatbot.message', verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Chat Feedback',
                'verbose_name_plural': 'Chat Feedback',
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-updated_at'], name='chatbot_con_user_id_0be7ed_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_active'], name='chatbot_con_is_acti_cbeff5_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chatbot_mes_convers_b353f0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['role'], name='chatbot_mes_role_028558_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatfeedback',
            unique_together={('message',)},
        ),
    ]
