# Generated by Django 5.1.4 on 2026-05-06 12:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='A human-readable name for this automation rule', max_length=200, verbose_name='Rule Name')),
                ('description', models.TextField(blank=True, help_text='Optional description of what this rule does', verbose_name='Description')),
                ('trigger_event', models.CharField(choices=[('EMPLOYEE_CREATED', 'Employee Created'), ('LEAVE_REQUESTED', 'Leave Requested'), ('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_REJECTED', 'Leave Rejected'), ('ATTENDANCE_MARKED', 'Attendance Marked'), ('PAYROLL_PROCESSED', 'Payroll Processed'), ('REVIEW_SUBMITTED', 'Review Submitted')], help_text='The HRMS event that triggers this rule', max_length=50, verbose_name='Trigger Event')),
                ('condition_expression', models.JSONField(blank=True, default=dict, help_text="JSON conditions to filter when the action should execute (e.g., {'status': 'ABSENT'})", verbose_name='Condition Expression')),
                ('action_type', models.CharField(choices=[('SEND_NOTIFICATION', 'Send Notification'), ('UPDATE_FIELD', 'Update Field'), ('CREATE_RECORD', 'Create Record'), ('TRIGGER_WEBHOOK', 'Trigger Webhook')], help_text='The type of action to perform when triggered', max_length=50, verbose_name='Action Type')),
                ('action_config', models.JSONField(blank=True, default=dict, help_text='JSON configuration for the action (e.g., notification message, field to update)', verbose_name='Action Configuration')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this rule', verbose_name='Active')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are evaluated first', verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Automation Rule',
                'verbose_name_plural': 'Automation Rules',
                'ordering': ['-priority', 'name'],
                'indexes': [models.Index(fields=['trigger_event', 'is_active'], name='hrms_automa_trigger_c06cef_idx'), models.Index(fields=['priority'], name='hrms_automa_priorit_11940f_idx')],
            },
        ),
    ]
