# Generated by Django 5.1.4 on 2026-05-06 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_automationrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_provider', models.CharField(choices=[('DEEPSEEK', 'DeepSeek'), ('OPENAI', 'OpenAI')], default='DEEPSEEK', help_text='Select the AI provider for chatbot and AI features', max_length=20, verbose_name='AI Provider')),
                ('deepseek_api_key', models.CharField(blank=True, help_text='API key for DeepSeek (https://api.deepseek.com)', max_length=500, verbose_name='DeepSeek API Key')),
                ('deepseek_base_url', models.CharField(blank=True, default='https://api.deepseek.com/v1', max_length=500, verbose_name='DeepSeek Base URL')),
                ('deepseek_model', models.CharField(blank=True, default='deepseek-chat', max_length=100, verbose_name='DeepSeek Model')),
                ('openai_api_key', models.CharField(blank=True, help_text='API key for OpenAI (https://api.openai.com)', max_length=500, verbose_name='OpenAI API Key')),
                ('openai_base_url', models.CharField(blank=True, default='https://api.openai.com/v1', max_length=500, verbose_name='OpenAI Base URL')),
                ('openai_model', models.CharField(blank=True, default='gpt-4o-mini', max_length=100, verbose_name='OpenAI Model')),
                ('embedding_model', models.CharField(blank=True, default='text-embedding-ada-002', max_length=100, verbose_name='Embedding Model')),
                ('max_tokens', models.IntegerField(default=4096, verbose_name='Max Tokens')),
                ('temperature', models.FloatField(default=0.7, verbose_name='Temperature')),
                ('notify_leave_requests', models.BooleanField(default=True, verbose_name='Notify on Leave Requests')),
                ('notify_payroll_updates', models.BooleanField(default=True, verbose_name='Notify on Payroll Updates')),
                ('notify_attendance_anomalies', models.BooleanField(default=True, verbose_name='Notify on Attendance Anomalies')),
                ('notify_performance_reviews', models.BooleanField(default=True, verbose_name='Notify on Performance Reviews')),
                ('notify_new_employees', models.BooleanField(default=True, verbose_name='Notify on New Employees')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
